tap "acrogenesis/macchanger"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "tidwall/jj"
tap "vitorgalvao/tiny-scripts"
cask "osxfuse"
brew "ack"
brew "apktool"
brew "openssl@1.1"
brew "asciinema"
brew "coreutils"
brew "asdf"
brew "bat"
brew "python@3.8", link: true
brew "webp"
brew "ffmpeg"
brew "cmus"
brew "cocoapods"
brew "cowsay"
brew "ctop"
brew "curl"
brew "deno"
brew "emacs"
brew "exa"
brew "ext4fuse"
brew "fd"
brew "feh"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "gifski"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "gpac"
brew "graphicsmagick"
brew "htop"
brew "httrack"
brew "hub"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ifstat"
brew "ios-deploy"
brew "lazydocker"
brew "libpq"
brew "libressl"
brew "libxml2"
brew "mas"
brew "mitmproxy"
brew "modd"
brew "youtube-dl"
brew "mpv"
brew "ncdu"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "netcat"
brew "nmap"
brew "nnn"
brew "opus-tools"
brew "osx-cpu-temp"
brew "pgcli"
brew "pngcheck"
brew "postgresql", restart_service: true
brew "postgresql@12"
brew "potrace"
brew "redis", restart_service: true
brew "ripgrep"
brew "sassc"
brew "scrcpy"
brew "speedtest-cli"
brew "stow"
brew "subversion"
brew "telnet"
brew "tmux"
brew "tree"
brew "watchman"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "mongodb/brew/mongodb-community"
brew "tidwall/jj/jj"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "adoptopenjdk8"
cask "alfred"
cask "alt-tab"
cask "android-platform-tools"
cask "android-studio"
cask "balenaetcher"
cask "blender"
cask "brave-browser"
cask "calibre"
cask "chromium"
cask "cyberduck"
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "dozer"
cask "epic-games"
cask "firefox"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-firacode-nerd-font"
cask "font-inter"
cask "gas-mask"
cask "godot"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "handbrake"
cask "iina"
cask "insomnia"
cask "iterm2"
cask "jdownloader"
cask "kap"
cask "keka"
cask "keycastr"
cask "ledger-live"
cask "lepton"
cask "lulu"
cask "mactex"
cask "mochi"
cask "mongodb-compass"
cask "ngrok"
cask "notion"
cask "numi"
cask "obs"
cask "pgadmin4"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "responsively"
cask "slack"
cask "sloth"
cask "spotify"
cask "steam"
cask "teamspeak-client"
cask "teamviewer"
cask "telegram"
cask "texstudio"
cask "textual"
cask "tor-browser"
cask "transmission"
cask "tunnelblick"
cask "veracrypt"
cask "vimr"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "vnc-viewer"
cask "wechat"
cask "whatsapp"
cask "windscribe"
cask "wireshark"
cask "xquartz"
mas "Amphetamine", id: 937984704
mas "DevCleaner", id: 1388020431
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "HiddenMe", id: 467040476
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "Twenttty", id: 1534796314
mas "Xcode", id: 497799835
mas "虾米音乐", id: 673877994
