code --install-extension adpyke.codesnap
code --install-extension alefragnani.Bookmarks
code --install-extension andys8.jest-snippets
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension asvetliakov.vscode-neovim
code --install-extension austenc.tailwind-docs
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bubersson.theme-hop-light
code --install-extension bungcip.better-toml
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-faker
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dunstontc.viml
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension GitHub.vscode-pull-request-github
code --install-extension heybourn.headwind
code --install-extension humao.rest-client
code --install-extension joelday.docthis
code --install-extension johnpapa.vscode-peacock
code --install-extension karigari.chat
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension KnisterPeter.vscode-commitizen
code --install-extension liviuschera.noctis
code --install-extension matklad.rust-analyzer
code --install-extension miguelsolorio.min-theme
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-pg
code --install-extension Nash.awesome-flutter-snippets
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension pascalpixel.cameo
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension Prisma.vscode-graphql
code --install-extension ritwickdey.LiveServer
code --install-extension serayuzgur.crates
code --install-extension Shan.code-settings-sync
code --install-extension silvenon.mdx
code --install-extension stylelint.vscode-stylelint
code --install-extension teabyii.ayu
code --install-extension toba.vsfire
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vadimcn.vscode-lldb
code --install-extension vscodevim.vim
code --install-extension wix.glean
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzane.markdown-pdf
