echo "patching default macOS apps..."
duti -s com.colliderli.iina .mp4 all
duti -s com.colliderli.iina .mov all
duti -s com.colliderli.iina .webm all
duti -s com.colliderli.iina .avi all
duti -s com.apple.TextEdit .txt all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .go all
duti -s com.microsoft.VSCode .py all
duti -s com.microsoft.VSCode .js all
duti -s com.microsoft.VSCode .ts all
duti -s com.microsoft.VSCode .c all
duti -s com.microsoft.VSCode .cpp all
duti -s com.microsoft.VSCode .h all
duti -s com.microsoft.VSCode .hpp all
duti -s com.microsoft.VSCode .java all
duti -s com.microsoft.VSCode .sh all
duti -s com.microsoft.VSCode .zsh all
duti -s com.microsoft.VSCode .bash all
duti -s com.microsoft.VSCode .fish all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .xml all
duti -s com.microsoft.VSCode .css all
duti -s com.microsoft.VSCode .scss all
duti -s com.microsoft.VSCode .sass all
duti -s com.microsoft.VSCode .less all
duti -s com.microsoft.VSCode .vue all
duti -s com.microsoft.VSCode .tsx all
duti -s com.microsoft.VSCode .jsx all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .rb all
duti -s com.microsoft.VSCode .rs all
duti -s com.microsoft.VSCode .swift all
duti -s com.microsoft.VSCode .kt all
duti -s com.microsoft.VSCode .dart all
duti -s com.microsoft.VSCode .sql all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .toml all
duti -s com.microsoft.VSCode .ini all
duti -s com.microsoft.VSCode .conf all
duti -s com.microsoft.VSCode .log all
duti -s com.apple.iWork.Numbers .csv all
duti -s com.apple.iWork.Numbers .tsv all
